services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - "$HOME/pcloud-sync/telaclass-content:/app/content/disciplinas:ro"
    ports:
      - "3000:3000"