services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app # Código host → contêiner (hot-reload)
      - /app/node_modules # Mantém node_modules só dentro do contêiner
    ports:
      - "3000:3000"